### ISSUE TITLE
Error running pulumi refresh on CloudFront distribution

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-terraform#165]
_From @chrsmith on June 5, 2018 4:38_

Running `pulumi refresh` on an `aws.cloudfront.Distribution` leads to an unexpected error.

Not sure the right repo to put this in. I assume this is some type of error in the AWS terraform provider? Or is it `pulumi` that handles the type mapping? Regardless, I assume this shouldn't be the case.

```
$ pulumi refresh
Previewing refresh of stack 'www.pulumi.com-chris'
Previewing changes:

     Type                 Name                                 Plan          Info
 *   pulumi:pulumi:Stack  www.pulumi.com-www.pulumi.com-chris  no change     1 error

Diagnostics:
  pulumi:pulumi:Stack: www.pulumi.com-www.pulumi.com-chris
    error: diffing urn:pulumi:www.pulumi.com-chris::www.pulumi.com::aws:cloudfront/distribution:Distribution::cdn: active_trusted_signers: 1 error(s) decoding:

    * '[items]' expected type 'string', got unconvertible type '[]interface {}'
```

_Copied from original issue: pulumi/pulumi#1462_

**Comment by lukehoban** [comment]
Also hit in https://github.com/pulumi/pulumi/issues/1711.

We definitely want to prioritize getting this one fixed - it's a common use case for `pulumi refresh`.

**Comment by swgillespie** [comment]
I'm probably not going to have time to hit this in M16.

**Comment by swgillespie** [comment]
Okay, this issue is pretty gnarly and the fix is best summarized as "we need to fix Refresh".

The root cause of this particular issue is that we are conflating Terraform state and Terraform config when doing refreshes in a way that Terraform is not OK with. `active_trusted_signers` is a computed `TypeMap` which is never expected to be in config, since it can't be specified by user programs. However, it ends up there when doing refreshes because we use Terraform state as "new" inputs when diffing against existing state.

To really fix this issue we need to re-think how we're doing refresh.
