### ISSUE TITLE
Avoid needing to pass extra properties to `.get`

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-terraform#266]
Today, `.get` takes an `id` and an optional bag of additional values.

When this is needed, it feels very awkward - it's both unclear why it is needed, and it is normally exactly duplicative of the `id`.

I believe that we might be able to get rid of the need for this entirely by invoking the `Importer` before the `Read`.  

For example, for `aws_lambda_function` - the `Importer` looks like:

```go
                Importer: &schema.ResourceImporter{
			State: func(d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
				d.Set("function_name", d.Id())
				return []*schema.ResourceData{d}, nil
			},
		},
```

This is exactly the custom code we need to turn just an ID into a bag with enough properties to invoke `Read`.  I believe this is generally the contract for `Importer`.  As a result, the `tfbridge` code ideally invoke this prior to invoking the `Read` method.

**Comment by lukehoban** [comment]
See also https://github.com/pulumi/pulumi-gcp/issues/48.

**Comment by joeduffy** [comment]
My anecdotal (and unfortunate) experience has been that TF providers semi-randomly decide that to read or import a resources state, the code needs more than just an ID. If that's not true for importers, great, although I'm skeptical we will find that there are importers for exactly the set of resources for which the ID alone is insufficient...

**Comment by joeduffy** [comment]
Also what confuses me is, if an importer can do this, why can't read? If read could have been written to just use ID, should we upstream fixes that do so? Or is there a subtle reason this makes sense for import but not read? (Possible)

**Comment by lukehoban** [comment]
Good questions, but two things:
1. This appears to solve at least all currently known occurrences of this category of problems
2. I can’t see any reason why it hurts to call Import+Read instead of just Read. 

Given that, I’m not sure why we wouldn’t want to do this. I’m still curious if there are any remaining cases that wouldn’t work, and to understand why Terraform didn’t just push this semantic requiremnt down to Read. But I can think of reasons why they might have gone the path the appear to have

**Comment by joeduffy** [comment]
Would fixing read for the cases we know of work also?

**Comment by lukehoban** [comment]
> Would fixing read for the cases we know of work also?

Yes - but:
a. That's a non-scalable solution when there is a scalable solution available.
b. It requires upstreaming changes which it's not (yet?) clear Terraform proper wants/needs.

Unclear why exactly that would be preferable?

**Comment by joeduffy** [comment]
It's preferable for a few reasons. It appears that we do not actually understand wherher read versus import behave differently intentionally, versus those we have sampled randomly having fixed then issues. It's also simpler -- instead of interfacing with *both* import and read, which have different semantics that (again) we are ignorant of, we deal with just one. Finally the non-scalable bit is just not true. The TF providers are part of our code base. We must fix them where they are deficient.

**Comment by joeduffy** [comment]
Just to clarify, if it's the case that Import is designed to work with just IDs, and no additional properties, and Read is not, then great -- it sounds like this is the way to go.

It simply isn't obvious to me that this is true.

If it's the case that _some_ Read implementations work with IDs, but not others -- and that _some_ Import implementations work with just IDs, but not others -- by design -- then this seems like an incomplete solution are that our "sample" of methods simply leads us to believe this will work.

Further, I thought only a vast subset of resources have Import methods, which would mean this is probably an incomplete solution. (E.g., do the AWS API Gateway resources have importers? Those are some of the worst culprits of needing more than just the ID to Read.)

Really just trying to make sure we end up somewhere that we're confident has a solid design behind it.

**Comment by lukehoban** [comment]
I'm confused by this discussion.  Let me step back a bit.

Terraform has a well defined and fully supported way to turn an ID, name and a resource type into a fully initialized instance of a Terraform resource.  It's called `terraform import aws_instance.example i-abcd1234`, and it works by calling the Importer and then Read on the resource type specified.  See https://www.terraform.io/docs/import/usage.html. 

We want to do *exactly* the same thing in our `.get` routines - we also take as input an ID, name and resource type and aim to create a fully initialized resource.  

Our current implementation of this only calls Read, and Read in Terraform does not have any contract that it takes a single ID as input.  Read in Terraform is "refresh", and has historically been allowed to depend on as much state as it wants as long as that was established by Create and Update.  As a result, we have to take an unspecified options bag as well as the ID, whose usability is poor, and has lead to several user reported issues.

There's a reasonable archeological question to ask about why Terraform chose to add `Importer`s instead of "fixing" all their Read implementations (not really fixing, more changing the contract and adapting them to adhere to the new contract).  

But regardless of the answer to that, at this point the options are:
1. Do the same thing as Terraform which is fully supported and assumes the same contracts on providers that Terraform itself assumes.
2. Assume a different contract for Read than Terraform assumes, and in places where that contract is not satisfied push the burden onto Pulumi users (not Terraform users), until such time as we can upstream an unbounded number of "fixes" to match a contract which the Terraform providers do not appear to believe they are required to adhere.

I may still be missing something, but I haven't seen any argument for why (2) would be better than (1).  It's true we don't know why Terraform made the design design they did, but we know they made it, and that they now rely on it.

**Comment by lukehoban** [comment]
Missed that you had just replied before I sent the above :-).

> Really just trying to make sure we end up somewhere that we're confident has a solid design behind it.

Agreed - not trying to rush to a new design - but I do think this is the right path for fixing these issues.

> If it's the case that some Read implementations work with IDs, but not others -- and that some Import implementations work with just IDs, but not others -- by design -- then this seems like an incomplete solution are that our "sample" of methods simply leads us to believe this will work.

It's sort of beside the point that some Reads work with only ID.  That's not part of the contract, so some do and some don't.  What is critical is that Import *must* work with only an ID, because that's all that `terraform import` has.

> I thought only a vast subset of resources have Import methods, which would mean this is probably an incomplete solution. (E.g., do the AWS API Gateway resources have importers? Those are some of the worst culprits of needing more than just the ID to Read.)

I believe they've done a lot of work to improve this - and to your example all the API Gateway resources I looked at earlier do support these.  It would be interesting to understand how many still don't - and whether it would be better to (a) fall back to just calling Read or (b) not support `.get` until import support is added.  I'll make sure we get data on this before making any decision here.

**Comment by joeduffy** [comment]
A specific resource that I've seen has this issue is API Gateway Deployment objects, due to

https://github.com/terraform-providers/terraform-provider-aws/blob/72e8bb4fc26feac0f06860453e931972d6eb2528/aws/resource_aws_api_gateway_deployment.go#L103

I do not see an importer for this resource type. Am I just looking in the wrong place?

> What is critical is that Import must work with only an ID, because that's all that terraform import has.

This was precisely the thing I was trying to get at. If this is a _guarantee_ about how importers must work, then great, this approach will ensure that we can always read resources with importers.

If it isn't, then we have to realize that we're only improving the statistics, and that we'll still be in a situation that some resources can't be read using the ID alone.

I just grepped for calls to `.Get("` in AWS's `import_*` files and it came up empty, which is promising.

**Comment by jen20** [comment]
> Also what confuses me is, if an importer can do this, why can't read? If read could have been written to just use ID, should we upstream fixes that do so? Or is there a subtle reason this makes sense for import but not read? (Possible)

Importers exist for a couple of reasons:

- To allow read to be called (so-called "ID only refresh" https://github.com/hashicorp/terraform/pull/6262)
- To allow sub resources to be imported along with their parents - for example, an `aws_route_table` import also imports the routes: (https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/import_aws_route_table.go)

The second of these means that calling the importer in all cases is likely not the desired outcome?

**Comment by lukehoban** [comment]
> The second of these means that calling the importer in all cases is likely not the desired outcome?

I think we can safely ignore those additional sub resources.  We'll need to walk the returned array and get the one with the type and/or id that matches what was requested (in case the Importer re-ordered), but I see no issue with just ignoring additional resources.

Honestly, in the limit of time it wouldn't hurt to actually realize all of the objects returned here into the programming model as `Resource` instances with dependencies and strongly typed links between them - but in the near term I don't think our provide interface would support this, and we don't have any way to recreate strongly typed links such that these additional objects would be addressable.
