### ISSUE TITLE
Crash in pulumi-terraform

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-terraform#371]
A user is hitting a crash in `pulumi-terraform`.

```
pulumi:pulumi:Stack (foo-stack-name):
    panic: fatal: An assertion has failed: expected non-nil error with nil state during Update
    goroutine 102 [running]:
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/pkg/util/contract.failfast(...)
        /home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/pkg/util/contract.Assertf(0xc0006b7b00, 0x4a2d528, 0x33, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/pkg/util/contract/assert.go:33 +0x198
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Provider).Update(0xc0006d2100, 0x5218c40, 0xc000a8d950, 0xc000cf54a0, 0xc0006d2100, 0x4127601, 0xc000a8ee00)
        /home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:722 +0xcff
```

**Comment by jen20** [comment]
This appears to be triggered when the following steps are taken:

1. Create an `aws.iam.Role` using Pulumi
1. Remove the role somehow - perhaps via the AWS Console or CLI
1. Adjust the `assumeRolePolicy` value in the Pulumi program and run `pulumi up`

This sequence puts us in this code path:

https://github.com/pulumi/terraform-provider-aws/blob/72b780bca0d3875d07b780b024c10ca710b0d458/aws/resource_aws_iam_role.go#L241-L254

In there, we end up with a nil state and a nil error thanks to calling `d.SetId("")` and then returning `nil`, and assert, which is not a nice user experience for a condition which uncommon, is not actually invalid.

Terraform has a much narrower window to hit this, since it runs a refresh by default before updating. If we do this (using `pulumi update --refresh`), we see the entire role marked for recreation. Reproducing our non-refresh workflow with Terraform doesn't fail, but doesn't actually update the missing resource either.

To improve discoverability here, we should change the assertion in Update here to return a proper error message instead of asserting - I'll follow up with a PR for this.
