### ISSUE TITLE
Error when using S3 RemoteStateReference with assume role

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-terraform#530]
It seems `RemoteStateReference` doesn't work when using a provider that uses `assumeRole`.

#### Steps to reproduce

1. `pulumi up` the code from the gist below
1. If it errors out about the role not being assumable or bucket not available, this is likely because of eventual consistency errors from AWS, repeat `up` until you see the error below. 

#### Error output
```
RemoteStateReference % pulumi up
Previewing update (dev):
     Type                                     Name                      Plan     Info
     pulumi:pulumi:Stack                      RemoteStateReference-dev           1 error
     └─ terraform:state:RemoteStateReference  main                               1 error
 
Diagnostics:
  pulumi:pulumi:Stack (RemoteStateReference-dev):
    error: preview failed
 
  terraform:state:RemoteStateReference (main):
    error: Preview failed: unrecognized resource type (Read): terraform:state:RemoteStateReference
 

RemoteStateReference % 
```

#### Code

https://gist.github.com/clstokes/5ef711bde385f3a8f8149755cfc3dc6c

**Comment by lukehoban** [comment]
So the problem here is that this code:

```
const tfStateAssumeRole = new terraform.state.RemoteStateReference("assume-role", {
    backendType: "s3",
    bucket: tfStateBucket.bucket,
    key: tfStateBucketObject.key,
}, { provider: assumeRoleProvider });
```

Is trying to use an `aws` provider to configure a resource from the `terraform` provider.  These are different providers, so this is equivalent to passing an Azure provider for an AWS resource to use.  

I'm surprised it doesn't error in a cleaner way (perhaps that is what the error here is really trying to say).  But that is expected.

As for *how* to actually configure the Terraform remote state provider's S3 connection - I believe you can use https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/terraform/state/#S3RemoteStateReferenceArgs-roleArn and friends.

**Comment by clstokes** [comment]
Yep, that makes sense - user error on my part. The code below works:

```ts
const tfStateAssumeRole = new terraform.state.RemoteStateReference("assume-role", {
    backendType: "s3",
    bucket: tfStateBucket.bucket,
    key: tfStateBucketObject.key,
    region: aws.config.requireRegion(),

    accessKey: myAccessKey,
    secretKey: mySecretKey,
    roleArn: allowS3ManagementRole.arn,
});
```
